### ISSUE TITLE
uploading a 4gb file timeout

### ISSUE THREAD

**Issue by mbamber1986** [Huntereb/Awoo-Installer#105] opened 2020-09-28 21:00 UTC
uploading a game to my switch of 4gb has no issues with goldleaf but awoo seems to fail install and says the reason is a timeout error

**Comment by Huntereb** [comment] 2020-09-29 00:47
Duplicate of #85 . You have a shitty USB cable, or your PC is taking too long to reply.

**Closed by Huntereb** 2020-09-29 00:47 UTC
